name: news
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  go_router: ^14.2.3
  intl: ^0.19.0
  json_annotation: ^4.9.0
  provider: ^6.1.2
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"
  pretty_dio_logger: ^1.3.1 
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
